### ISSUE TITLE
Emails are sent when mailbox is defined

### ISSUE THREAD

**Issue by krosseyed** [mimecorg/webissues-server#2]
I am running into an issue when configuring webissues inbox settings.

When the mailbox is defined, the php mailer sends out an email to anyone that emails me. This is unexpected as I wanted to have the server send an email when it sees a labeled message.

Please let me know what logs are needed to troubleshoot this issue.

**Comment by mimecorg** [comment]
The inbox can be configured to only process messages from a certain folder, so you can configure a rule which automatically moves emails to that folder based on some criteria.

**Comment by krosseyed** [comment]
That is my understanding, however when I set up the mailbox to use a certain folder in my IMAP account it does not respect it and will respond whenever anyone emails me.

Hope this helps explain better. Here is a screenshot of my current configuration

<img width="614" alt="webissues_issue_npi" src="https://user-images.githubusercontent.com/6548354/64611233-9a5f4200-d396-11e9-833d-96d1f414da9d.PNG">

**Comment by mimecorg** [comment]
What kind of email server do you use? This should work, but unfortunately PHP support for IMAP isn’t reliable in all cases.

**Comment by krosseyed** [comment]
I am using Gmail to handle IMAP and SMTP. Is there a log that I can look for that will help me troubleshoot why its pulling from my main mailbox, vs the label/folder I created in Gmail?

This has worked in the past, but it began after I had migrated between one server to another. Also, I have added in folder mapping to see if that would fix the issue, but it does not.

**Comment by krosseyed** [comment]
I figured out what it was!

It looks like Gmail uses lowercase characters for label names. I just changed my mailbox name to "tickets" and it is working now.

Thanks for getting back to me, and thank you for making webissues!

**Comment by krosseyed** [comment]
Well, looks like its still broken. I had disabled sending email while troubleshooting this, and it still responds and creates a ticket for every email that comes in, vs emails that are labeled.
